export const STEPS = [
  {
    id: "overview",
    label: "Overview",
    title: "Product overview",
    sub: "Define the product at the highest level",
    icon: "📄",
    fields: [
      { id: "product_name", label: "Product name", type: "text", req: true, hint: "What is this product called?", placeholder: "e.g. TaskFlow, HealthTrack, ShopBot" },
      { id: "one_liner", label: "One-liner description", type: "text", req: true, hint: "Describe the product in one sentence", placeholder: "e.g. A mobile app that helps freelancers track billable hours automatically" },
      { id: "product_type", label: "Product type", type: "chips", req: true, hint: "Select all that apply", opts: ["Mobile app","Web app","Desktop app","API / backend","Browser extension","Hardware + software","Data platform","AI/ML product","Internal tool","SaaS"] },
      { id: "stage", label: "Current stage", type: "chips", req: true, hint: "Where are you in the journey?", opts: ["Idea / concept","Validation / MVP","Alpha","Beta","Live — new feature","Redesign","Scaling"] },
    ],
  },
  {
    id: "problem",
    label: "Problem",
    title: "Problem & opportunity",
    sub: "What pain does this solve, and for whom?",
    icon: "🎯",
    fields: [
      { id: "problem_statement", label: "Problem statement", type: "textarea", req: true, hint: "Describe the core problem in 2–4 sentences.", placeholder: "e.g. Freelancers lose an average of 20% of billable hours because they forget to log time during calls and context switches..." },
      { id: "who_has_problem", label: "Who experiences this problem", type: "textarea", req: true, hint: "Be specific — not 'everyone' or 'businesses'", placeholder: "e.g. Solo freelancers and small agencies (2–10 people) doing client work in design, development, or consulting" },
      { id: "how_solved_today", label: "How people solve it today", type: "textarea", req: false, hint: "Describe current workarounds", placeholder: "e.g. Toggl, spreadsheets, post-it notes, or just guessing at invoice time" },
      { id: "why_now", label: "Why is now the right time?", type: "textarea", req: false, hint: "Market shifts, tech availability, competitor gaps", placeholder: "e.g. Remote work normalization increased the number of freelancers 40% since 2020..." },
    ],
  },
  {
    id: "users",
    label: "Users",
    title: "Users & personas",
    sub: "Who is this for, specifically?",
    icon: "👥",
    fields: [
      { id: "primary_persona", label: "Primary user persona", type: "textarea", req: true, hint: "Name, role, context, goals, frustrations — be concrete", placeholder: "e.g. 'Alex, 32, freelance UI designer. Works from home, juggles 3–5 clients. Goal: get paid accurately without admin overhead.'" },
      { id: "secondary_persona", label: "Secondary persona (optional)", type: "textarea", req: false, hint: "A second user type if applicable", placeholder: "e.g. Agency owner who reviews team utilization reports" },
      { id: "user_count", label: "Estimated user base (Year 1)", type: "chips", req: false, hint: "Rough order of magnitude", opts: ["< 100 users","100 – 1,000","1,000 – 10,000","10,000 – 100,000","100,000+","B2B (seats / orgs)"] },
      { id: "user_tech", label: "User tech comfort level", type: "chips", req: false, hint: "Affects UX complexity decisions", opts: ["Non-technical","Moderate","Technical","Developer audience","Mixed"] },
    ],
  },
  {
    id: "goals",
    label: "Goals",
    title: "Goals & success metrics",
    sub: "What does success look like, concretely?",
    icon: "📊",
    fields: [
      { id: "north_star", label: "North star metric", type: "text", req: true, hint: "The single most important metric that proves the product is working", placeholder: "e.g. Weekly active users who log at least 1 hour, Monthly recurring revenue, NPS > 50" },
      { id: "business_goals", label: "Business goals", type: "textarea", req: true, hint: "What does the organization need from this product?", placeholder: "e.g. Reach $10k MRR within 6 months, establish foothold in SMB market" },
      { id: "user_goals", label: "User success criteria", type: "textarea", req: true, hint: "How does the user know the product worked for them?", placeholder: "e.g. User invoices correctly for 95%+ of hours worked without manual logging" },
      { id: "anti_goals", label: "Anti-goals (what this is NOT)", type: "textarea", req: false, hint: "Explicitly stating what you won't do prevents scope creep", placeholder: "e.g. This is not a full accounting or invoicing tool. It does not replace Quickbooks." },
    ],
  },
  {
    id: "features",
    label: "Features",
    title: "Features & scope",
    sub: "What does the product actually do?",
    icon: "⚡",
    fields: [
      { id: "must_have", label: "Must-have features (MVP)", type: "textarea", req: true, hint: "List the features without which the product doesn't work. One per line.", placeholder: "- Automatic time detection\n- Manual time entry override\n- Client / project tagging\n- Weekly summary report\n- CSV export" },
      { id: "should_have", label: "Should-have features (v1.1+)", type: "textarea", req: false, hint: "Important but not blocking launch", placeholder: "- Slack integration\n- Invoicing template generation\n- Team / agency view" },
      { id: "wont_have", label: "Explicitly out of scope", type: "textarea", req: false, hint: "Things people will ask for that you'll say no to in v1", placeholder: "- Payment processing\n- Expense tracking\n- Mobile app (web first)" },
      { id: "feature_priority", label: "Prioritization framework", type: "chips", req: false, hint: "How will you decide what to build first?", opts: ["MoSCoW","RICE scoring","Kano model","Jobs-to-be-done","Gut feel / founder intuition","Customer interviews","Data-driven (analytics)"] },
    ],
  },
  {
    id: "technical",
    label: "Technical",
    title: "Technical requirements",
    sub: "Constraints, stack, and non-functionals",
    icon: "🔧",
    fields: [
      { id: "platform", label: "Target platform(s)", type: "chips", req: true, hint: "Where does this run?", opts: ["iOS","Android","Web (browser)","macOS","Windows","Linux","API only","Embedded / IoT","Cross-platform"] },
      { id: "tech_stack", label: "Preferred / existing tech stack", type: "textarea", req: false, hint: "Languages, frameworks, cloud providers — or 'TBD'", placeholder: "e.g. React frontend, Node.js + Express API, PostgreSQL, AWS" },
      { id: "non_functional", label: "Non-functional requirements", type: "chips", req: false, hint: "Which quality attributes matter most?", opts: ["< 2s load time","99.9% uptime","GDPR compliance","HIPAA compliance","SOC 2","Offline support","Accessibility (WCAG 2.1)","Multi-language / i18n","End-to-end encryption","Horizontal scalability"] },
      { id: "integrations", label: "Required integrations", type: "textarea", req: false, hint: "External systems this must connect to", placeholder: "e.g. Google Calendar, Slack, Stripe, Zapier" },
    ],
  },
  {
    id: "timeline",
    label: "Timeline",
    title: "Timeline & constraints",
    sub: "Deadlines, team, and budget",
    icon: "📅",
    fields: [
      { id: "launch_target", label: "Target launch date", type: "text", req: false, hint: "Approximate is fine — quarter, month, or milestone", placeholder: "e.g. Q3 2025, 3 months from kickoff, before annual conference" },
      { id: "milestones", label: "Key milestones", type: "textarea", req: false, hint: "Discovery → design → build → test → launch", placeholder: "Week 1–2: discovery & wireframes\nWeek 3–6: MVP build\nWeek 7: internal testing\nWeek 8: beta with 10 users\nWeek 10: public launch" },
      { id: "team", label: "Team & roles", type: "textarea", req: false, hint: "Who is building this?", placeholder: "e.g. 1 founder (PM + design), 1 contract developer, AI-assisted coding" },
      { id: "constraints", label: "Known constraints", type: "textarea", req: false, hint: "Budget, tech debt, regulatory, skill gaps", placeholder: "e.g. Bootstrap budget — no paid infrastructure > $200/month" },
    ],
  },
  {
    id: "risks",
    label: "Risks",
    title: "Risks & open questions",
    sub: "What could kill this, and what don't you know yet?",
    icon: "🛡️",
    fields: [
      { id: "top_risks", label: "Top 3 risks", type: "textarea", req: false, hint: "Technical, market, or execution risks", placeholder: "1. Automatic detection accuracy < 80%\n2. Core use case already solved by Toggl\n3. Privacy concerns around app activity monitoring" },
      { id: "assumptions", label: "Key assumptions being made", type: "textarea", req: false, hint: "What must be true for this to work?", placeholder: "- Users will allow activity monitoring if they control the data\n- Freelancers would pay $15/month to recover lost billing" },
      { id: "open_questions", label: "Open questions to resolve", type: "textarea", req: false, hint: "What do you need to answer before building?", placeholder: "- Should we build mobile-first or web-first?\n- What's the minimum viable detection accuracy users accept?" },
      { id: "competitors", label: "Competitors & differentiation", type: "textarea", req: false, hint: "Who else plays here, and why will yours win?", placeholder: "e.g. Toggl (manual), Harvest (manual + invoicing). Gap: none combine automatic detection with client billing context." },
    ],
  },
];
